### ISSUE TITLE
Issues with SplitCrossEntropyLoss

### ISSUE THREAD

**Issue by ccarter-cs** [salesforce/awd-lstm-lm#30]
1) Parameters in SplitCrossEntropyLoss are not being updated since they are missing from the optimizer.
2) Parameters in SplitCrossEntropyLoss are being initialized to 0. EDIT: After reflection, I'm not sure this matters.

Locally, I fixed these issues and ran some very short experiments on 140 batches on wikitext-103 as follows:
  - [master.txt](https://github.com/salesforce/awd-lstm-lm/files/1857425/master.txt) are results for code at commit 1e24cc54 (current master)
  - [optimizerfix.txt](https://github.com/salesforce/awd-lstm-lm/files/1857431/optimizerfix.txt) are the results with the issue 1 fixed
  - [initializationfix.txt](https://github.com/salesforce/awd-lstm-lm/files/1857434/initializationfix.txt) are the results with issue 1 fixed as well as the parameters being initialized the same as the embeddings.

**Comment by daemon** [comment]
Have you managed to reproduce standard results with these fixes?

**Comment by ccarter-cs** [comment]
All of my GPU resources are occupied with my own work at the moment, or I would have already run it. If no-one else has a chance to test, I'll get to it at some point.

**Comment by daemon** [comment]
Sounds good. I'll keep you updated as well.

**Comment by Smerity** [comment]
Oh dear, this is very much an issue, and indeed a bug I had and then fixed in my internal implementation. The code here is a result of applying what is the equivalent of a manual diff between the two codebases.

I will start writing a fix for this. Thanks for noticing this - though sorry I put you in that position! :(

If you're curious why the "broken" version improves faster, there is zero way for the broken version to improve the probability of rare words, so it instead focuses on fixing frequent words, which are the majority of the tokens in the dataset. Hence it will have better early convergence properties but then hard plateau when it gets stuck later.

**Comment by Smerity** [comment]
Oh, regarding initialization, I don't personally believe that the initialization of the parameters is of extreme importance but I am frequently silly and also wrong, sooooooo ^_^

**Comment by Smerity** [comment]
This commit should fix the issue (and also ensures gradient clipping is applied to all the gradients too):
https://github.com/salesforce/awd-lstm-lm/commit/1f0982e861b1f98ffb0564861d06105c23accf0b

I will close this issue when I can confirm it trains as expected. I'm starting a P100 or V100 on that now.

Sorry again for the issue and slow reply =[

**Comment by Smerity** [comment]
I have successfully reproduced the original result after fixing both this issue and minor issues with the command (i.e. wrong wdrop value and somehow using LSTM instead of QRNN? -_-)

Hopefully that should be good now but otherwise open other specific issues! :)
